version: '3.6'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 7000:8080
    restart: always
    volumes:
      - './swagger.json:/swagger.json'
    environment:
      SWAGGER_JSON: ${SWAGGER_JSON}
  metrics:
    image: 'prom/prometheus:latest'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #  ganache:
  #    image: 'trufflesuite/ganache:latest'
  #    ports:
  #      - '8545:8545'
  #    command: '--mnemonic "field harbor junk ship this damp amateur meat cushion odor above attend" --gasLimit 10000000 --accounts 10 --chain.chainId 1337'
  geth:
    image: custom-geth
    build:
      context: ./crates/geth/
      dockerfile: Dockerfile
    ports:
      - '30303:30303'
      - '8545:8545'
    command: [ "--port", "30303", "--nodiscover", "--unlock", "0xff93B45308FD417dF303D6515aB04D9e89a750Ca,0x8e0a907331554AF72563Bd8D43051C2E64Be5d35,0x24962717f8fA5BA3b931bACaF9ac03924EB475a0,0x148FfB2074A9e59eD58142822b3eB3fcBffb0cd7,0x4CEEf6139f00F9F4535Ad19640Ff7A0137708485", "--password", "/tmp/password.txt", "--http", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.corsdomain", "\"*\"", "--networkid", "5", "--dev.gaslimit", "8000000", "--allow-insecure-unlock", "--mine" ]
  chainbridge-deploy:
    image: chainbridge-deploy
    build:
      context: .
      dockerfile: chainbridge-deploy.Dockerfile
    restart: on-failure
    command: "--url http://172.17.0.1:8545 deploy --all --relayerThreshold 1"
    links:
      - geth